version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: jwt_auth_practica_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: auth_db
    ports:
      - "5435:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: jwt_auth_ppg
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5544:80"
    depends_on:
      - postgres